services:
  mariadb:
    image: mariadb:latest
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sweaters
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    container_name: mariadb
  sweaterapp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/io
    container_name: sweaters


